# Generated by Django 4.2.6 on 2023-10-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_user_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscrioption',
            new_name='Subscription',
        ),
    ]
